name: youapp_tester
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  collection: ^1.18.0
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  image_picker: ^1.1.2
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  recase: ^4.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.9
  mocktail: ^1.0.4
  json_serializable: ^6.8.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
